### ISSUE TITLE
Install of the cef binaries is missing in CMakeLists

### ISSUE THREAD

**Issue by L-Trump** [Almamu/linux-wallpaperengine#216]
This cause problems on packaging. After installing by the PKGBUILD in my ArchLinux. Following error occurs:
```bash
> linux-wallpaperengine
linux-wallpaperengine: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory
```

After packaging, only few files are involved:
```bash
> pacman -Ql linux-wallpaperengine-git
linux-wallpaperengine-git /usr/
linux-wallpaperengine-git /usr/bin/
linux-wallpaperengine-git /usr/bin/linux-wallpaperengine
linux-wallpaperengine-git /usr/share/
linux-wallpaperengine-git /usr/share/linux-wallpaperengine/
linux-wallpaperengine-git /usr/share/linux-wallpaperengine/patches/
linux-wallpaperengine-git /usr/share/linux-wallpaperengine/patches/lens_flare_sun.frag.json
linux-wallpaperengine-git /usr/share/linux-wallpaperengine/patches/vhstest.vert.json
linux-wallpaperengine-git /usr/share/linux-wallpaperengine/patches/water_caustics.frag.json
```

Maybe it's better to use a system-wide cef dependency?

**Comment by sweglord227** [comment]
had the same issue, not present when building manually. this is likely a problem with the package build rather than the repo itself.

**Comment by milkydelta** [comment]
I think this might have been fixed recently. I'm using the aur package and I don't get any complaints about the missing cef file.

**Comment by Almamu** [comment]
Yes, arch's package should be fixed already, updating should suffice. Please re-open if the issue still persist.

**Comment by NoyingNabi** [comment]
Happening to me in Fedora 40, built it from source.

**Comment by Almamu** [comment]
Can you list the contents of /opt/linux-wallpaperengine? I have the suspicion it might not be the CEF files missing but the path where you're running the binary from. I need to find a better way of handling this scenario...

If you find CEF files in there, then cd'ing to /opt/linux-wallpaperengine before running anything should be enough to make it work. But as I've said, need to better handle this situation...

**Comment by NoyingNabi** [comment]
Yeah it works as long as I am on the folder, still dont know why it doesnt execute outside of that scope


chrome_100_percent.pak  chrome_200_percent.pak  chrome-sandbox  debug.log  icudtl.dat  libcef.so  libEGL.so  libGLESv2.so  libvk_swiftshader.so  linux-wallpaperengine  locales  resources.pak  share  snapshot_blob.bin  v8_context_snapshot.bin  vk_swiftshader_icd.json
